### ISSUE TITLE
Add properly configured .gitignore file

### ISSUE THREAD

**Issue by JohnKhandygo** [Alexandro9911/PrefixTree#1]
В .gitignore файле описываются файлы и директории, которые необходимо исключить при работе с данным репоиторием в git. В число таких файлов, как правило, включают специфичные для пользователей файлы, что позволяет избежать конфликтов при конкурентной работе с репозиторием. В частности, сюда целесообразно отнести файлы, [генерируемые IDE](https://intellij-support.jetbrains.com/hc/en-us/articles/206544839-How-to-manage-projects-under-Version-Control-Systems), поскольку их формат и содержание может отличаться от версии к версии. Для генерации .gitignore в idea удобно использовать [.ignore плагин](https://plugins.jetbrains.com/plugin/7495--ignore).

**Comment by Alexandro9911** [comment]
Добавил gitignore

**Comment by Alexandro9911** [comment]
В gitignore добавил файлы .idea и iml но предыдущие версии остались в реп. видны. Их надо как-то убирать? Если да, то как?

**Comment by JohnKhandygo** [comment]
Во-первых, я не вижу в .gitignore директивы для iml файлов. Во-вторых, да, их надо удалять. Для удаление файлов, которые есть в .gitignore используйте команду [git-clean](https://git-scm.com/docs/git-clean).

**Comment by JohnKhandygo** [comment]
Тут мой косяк, команда не та. В удаленном репозитории все еще остались файлы из .gitignore. Инструкцию по удалению смотри [здесь](https://gist.github.com/scy/6636390).

**Comment by Alexandro9911** [comment]
проделал `git rm --cached --ignore-unmatch PrefixTree.iml`  и git rm -r --cached --ignore-unmatch .idea
Но ничего не сработало(  что делать?

**Comment by JohnKhandygo** [comment]
Не уверен, что опция `--ignore-unmatch` нужна. 

После выполнения этих команд надо сделать коммит и пуш, как обычно.

**Comment by Alexandro9911** [comment]
Странно, я вроде выполнил эту команду, командная строка вывела rm ```
'.idea/compiler.xml'
rm '.idea/description.html'
rm '.idea/encodings.xml'
rm '.idea/gradle.xml'
rm '.idea/misc.xml'
rm '.idea/modules.xml'
rm '.idea/uiDesigner.xml'
rm '.idea/vcs.xml'
```
сделал коммит и пуш, но ничего не поменялось

**Comment by Alexandro9911** [comment]
Странно, я выполнил команды командная строка вывела `rm '.idea/compiler.xml'
rm '.idea/description.html'
rm '.idea/encodings.xml'
rm '.idea/gradle.xml'
rm '.idea/misc.xml'
rm '.idea/modules.xml'
rm '.idea/uiDesigner.xml'
rm '.idea/vcs.xml'
`
коммит и пуш сделал, но ничего не произошло

**Comment by Alexandro9911** [comment]
Сделано

**Comment by JohnKhandygo** [comment]
Таки в итоге отработали команды или Вы ручками потерли? 

Спрашиваю, потому что у некторых возникает проблема, что эти команды не отрабатывают.

**Comment by Alexandro9911** [comment]
Не работало когда делал коммит через кнопку в идее. 
А когда ввел те же самые команды и сделал коммит и пуш через консоль все заработало. Делал по инструкции как вы писали Виталику Петрову.

**Comment by JohnKhandygo** [comment]
Очень интересно. Окей. Спасибо.
