### ISSUE TITLE
Use consistent code style/formatting

### ISSUE THREAD

**Issue by JohnKhandygo** [Alexandro9911/PrefixTree#3]
В исходном коде программы встречаются разночтения стиля кодирования/форматирования. В качестве референсного стиля кодирования можно использовать [google java style guide](https://google.github.io/styleguide/javaguide.html). 

Также в исходном коде крайне нежелательно наличие комментариев, которые не являются Javadoc'ом. Если Ваш код нельзя понять без комментариев, значит это плохой код.

**Comment by JohnKhandygo** [comment]
Актуально.

**Comment by Alexandro9911** [comment]
вроде поправил
