### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by JohnKhandygo** [Alexandro9911/PrefixTree#4]
По условиям первого задания весь разработанный код должен быть покрыт тестами. Для вычисления процента покрытия используйте [Run with Coverage](https://www.jetbrains.com/help/idea/running-with-coverage.html). От Вас, естественно, не требуется покрывать тестами такие методы, как `equals`, `hashCode` и `toString`.

**Comment by Alexandro9911** [comment]
добавил все тесты. но все еще актуально??

**Comment by JohnKhandygo** [comment]
А Вы и не писали, что исправили это замечание.

**Comment by JohnKhandygo** [comment]
Некоторые Ваши тесты вообще не работают. Некоторые в принципе ничего не проверяют (то есть проверяют заведомо корректные условия).

**Comment by Alexandro9911** [comment]
Исправил все тесты

**Comment by JohnKhandygo** [comment]
- Ваши тесты не очень хорошо организованы. Теперь, когда у Вас есть возможность получить все слова, которые содержатся в дереве, Вы можете проверить, какие именно слова есть в дереве после совершения операций. 
- Если в `AnotherTests` Вы тестируете функциональность класса `Node`, то лучше так и назвать этот класс --- `NodeTest`.

**Comment by Alexandro9911** [comment]
исправил тесты и удалил ненужные
