### ISSUE TITLE
Use common project structure

### ISSUE THREAD

**Issue by JohnKhandygo** [Alexandro9911/PrefixTree#6]
В java проектах принято файлы исходного кода организовать в определнной структуре папок. Описание одного из наиболее распространенных способов организации проекта смотри [здесь](https://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html) или [здесь](https://stackoverflow.com/questions/41638654/java-project-folder-structure-in-intellij-idea). 

Кроме того, в java принято орагнизовывать классы в пакеты. Общепринятые правила именования пакетов см. [здесь](https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html). Понятно, что у Вас скорее всего нет никакого сайта. В этом случае можно его придумать или взять название орагнизации, в рамках которой делается проект. Например, `org.spbstu.your_surname`.

Каждый файл исходного кода должен находится в структуре папок, соответствующей названию его пакета. Например, если файл исходного кода озаглавлен директивой `package com.mycompany.myname`, то этот файл должен располагаться по пути `com/mycompany/myname` относительно папки с исходным кодом внутри проекта.

**Comment by Alexandro9911** [comment]
Поправил структуру и добавил пакеты

**Comment by JohnKhandygo** [comment]
Внимательно прочитайте, что написано в ссылках, которые я скинул: в структуре папок не хватает директорий, имя пакета сформировано без учета общепринятых рекомендаций. Если проблема в английском, я найду Вам материалы на русском.

**Comment by Alexandro9911** [comment]
исправил?

**Comment by JohnKhandygo** [comment]
Нет. Табличку сделайте.

**Comment by Alexandro9911** [comment]
теперь вроде готово

**Comment by JohnKhandygo** [comment]
Идеально.
