### ISSUE TITLE
Upgrade impl.

### ISSUE THREAD

**Issue by JohnKhandygo** [Alexandro9911/PrefixTree#7]
- [x] В коде не должно быть лишних комментариев. Если Вам приходится писать комментарии для того, чтобы Ваш код был понятен, то это плохой код. 
- [x] В общем случае в коде не должно быть вызовов `System.out.println`. Если Вам необходимо логгирование действий программы, то для этого стоит использовать специальные библиотеки. Если Вам необходимо отладить свою программу, то следует аоспользоваться специальным режимом запуски программы в Вашей ide --- [debug](https://www.jetbrains.com/help/idea/debugging.html).
- [x] `child` --- это ребенок в единственном числе, у Вас же внутри экземпляра `Node` хранится множество узлов. Очень важно, чтобы имена переменных и методов соответствовали тому, что действительно делает эта перменная/метод.
- [x] Вместо `ArrayList` надо возвращать `List`, вместо `HashMap` --- `Map`. Это правило в общем работает и для всех остальных типов коллекций. 
- [x] Некоторые методы в `PrefixTrie` необходимы только для тестирования. Такие методы стоит вынести в тестовый пакет Вашей программы (отдельным классом или в класс с самими тестами) хотя бы ради того, чтобы они не захламляли основной код программы.
- [x] Метод `hasChild` реализован ужасно. Все, что Вы хотели в нем сделать можно записать одной командой.
- [x] Метод `input` всегда возвращает `true`. 
- [x]  Составление стэка узлов внутри метода `delete` очень похоже на то, что делает `listNodes`. Подумайте, может быть одинаковый код получится вынести в отдельный метод?
- [x] Метод `find` работает некорректно.
- [x] Вместо `new String()` лучше писать `""`. Подробности см. [здесь](https://stackoverflow.com/questions/3052442/what-is-the-difference-between-text-and-new-stringtext). Вообще idea такие (и многие другие) вещи подсвечивает. Не игнорируйте, наведите корсур, прочитайте сообщение. В большинстве случаев можно нажать `ctrl + Enter` для того, чтобы idea предложила варианты исправлений.
- [x] Не понятно, зачем Вам метод `findAllStrings`, который принимает `char`. Это должен быть просто частный случай метода `findAll`.
- [x] Функция `findAll` работает некорректно.

**Comment by Alexandro9911** [comment]
Вроде все исправил

**Comment by JohnKhandygo** [comment]
Ну почти. 
- [x] Мне кажется, что использование `TreeMap` внутри `Node` необосновано. Подробнее смотри [здесь](https://stackoverflow.com/questions/2444359/what-is-the-difference-between-a-hashmap-and-a-treemap).
- [ ] В java принято использовать наиболее "жесткую" из возможных областей видимости (private > package private > public). Приватные методы, конечно, не подлежат тестированию в таком случае. У Вас в коде есть несколько мест, в которых видимость членов класса можно усилить. 
- [x] Метод `Node::sizeof` реализован ужасно. Все, что Вы в нем хотели сделать, можно записать одной операцией.
- [x] Некоторые методы в `Node` существуют только потому, что Вы написали на них тест. Эти методы точно нужны?
- [x] Метод `PrefixTrie::input` работает неэффективно: Вы сначала делаете проход по всему слову, чтобы определить, есть ли оно уже в дереве (метод `find`) и, если нет, то делаете еще один проход по тому же слову. Можно избавиться от первого прохода?
- [x] А почему собственно, нельзя положить в дерево пустое слово?
- [x] Метод `PrefixTrie::delete` работает некорректно. Вы можете убедиться в этом как только исправите тесты в соответствии с моими рекомендациями.

**Comment by Alexandro9911** [comment]
доработал методы

**Comment by JohnKhandygo** [comment]
- [ ] С областями видимости Вам еще надо доразбираться.
- [x] `delete` все еще работает некорректно. Вы забыли про то, что у Вас теперь есть признак конца слова. Например, вот такой тест не будет работать:
  ```
  PrefixTrie a = new PrefixTrie();
  a.input("abcd");
  a.input("abcde");
  assertEquals(true, a.delete("abcd"));
  assertEquals(false, a.find("abcd"));
  ```

В остальном окей.

**Comment by Alexandro9911** [comment]
`Delete` починил.
По поводу области видимости, я правильно понял, что надо некоторые методы, которые являются служебными сделать приватными?

**Comment by JohnKhandygo** [comment]
Да, общий принцип примерно следующий: представьте, что Вашу разработку используют как библиотеку, тогда
- Публичными (`public`) являются методы, который должны быть доступны пользователю библотеки.
-  Видимость по умолчанию (package private) используются, когда некоторые методы переиспользуются ежду классами внутри одного пакета. 
- Приватная область видимости (`private`) используется когда метод должен быть доступен **только** внутри этого же класса. 

Поля классов, как правило, делают приватными, доступ к ним (если он нужен) организуют при помощи геттеров и сеттеров. При этом, если значение поля никогда не меняется, то имеет смысл объявить его `final` для того, чтобы избежать некоторых дурацких ошибок. В этом случае для поля не существует сеттера.

Также стоит отметить, что приватные методы не покрывают тестами напрямую. Просто потому, что к ним нет доступа извне класса, в котором они определены.

**Comment by Alexandro9911** [comment]
вроде все

**Comment by JohnKhandygo** [comment]
Окей. Вы вроде правильно уловили идею, но я бы все-таки сделал `PrefixTrie::root` и `PrefixTrie::listNodes` приватными.
