### ISSUE TITLE
Task 2.0

### ISSUE THREAD

**Issue by JohnKhandygo** [Alexandro9911/PrefixTree#8]
**Общая формулировка**
Разработать консольную утилиту, реализующую указанную в задании функциональность, на языках Java и/или Kotlin. При проектировании использовать объектно-ориентированный подход. Разработать автоматические тесты для отдельных частей программы. Написанный код держать в отдельном проекте или модуле в репозитории на GitHub.

**split**
Разбивает большой текстовый файл на маленькие файлы фиксированного размера. 

file задаёт имя входного файла.
Флаг -o ofile  задаёт базовое имя выходного файла. Если параметр отсутствует,  базовое имя выходного файла равняется “x”. Если параметр равен “-”, в качестве базового имени выходного файла следует использовать имя входного файла.
Флаг -d означает, что выходные файлы следует называть “ofile1, ofile2, ofile3, ofile4 …”, где ofile это базовое имя выходного файла. Если же этот параметр не указан, то файлы должны называться “ofileaa, ofileab, ofileac, ofilead … ofileaz ofileba ofilebb …  ”.
Флаг -l num указывает размер выходных файлов в строчках. По умолчанию выходные файлы имеют размер в 100 строчек.
Флаг -с num указывает размер выходных файлах в символах.
Флаг -n num указывает количество выходных файлов. Размер файлов при этом должен считаться автоматически.

Command line: split [-d] [-l num|-c num|-n num] [-o ofile] file

В случае, когда какое-нибудь из имён файлов указано неверно или одновременно указано несколько флагов управления размером, следует выдать ошибку. 

Кроме самой программы, следует написать автоматические тесты к ней.

**Comment by JohnKhandygo** [comment]
Проверку второго задания начну только после того, как будут закрыты все замечания к первому заданию. Если будет делать в другом репозитории, скииньте сюда ссылку.

В любом случае напишите в комментарии, когда это задание будет готово к проверке.

**Comment by JohnKhandygo** [comment]
Первое задание можете считать успешно закрытым, приступайте к следующему. Ниже не большая инструкция для упрощения выполнения задания.

Рекомендуется следующий подход к разработке:
1. Реализовать класс со всей необходимой логикой так, как Вы это делали в предыдущем задании (с покрытием тестами и прочим). Другими словами, забудьте на время, что Ваше приложение должно работать из консоли.
2. Отдельно написать "обертку", которая будет парсить аргументы командной строки (используя библиотеку) и вызывать разработанные на первом этапе методы. Скорее всего то, что будет написано на втором шаге, даже не потребуется покрывать тестами, поскольку функциональность сторонних библотек обычно не тестируется (либо тестируется в каких-то очень сложных случаях). 

Собственно после готовности первого этапа можно начинать проверку.

**Comment by Alexandro9911** [comment]
Проект будет тут: https://github.com/Alexandro9911/Spliter
Проект еще совсем сырой пока что. Создал класс к нему, и пара методов, и то не все. Через консоль они работают(один не верно) если запустить, а если создавать на них тесты, не работает, и выдает ошибку компиляции.
что то вроде:` java: package org.junit does not exist`

**Comment by JohnKhandygo** [comment]
Для удобства переношу условие задания в новый репозиторий. Все замечания будут появляться там.
